version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
  # streamlit:
  #   build:
  #     context: ./streamlit
  #   ports:
  #     - "8501:8501"
